### Site info:
title: Viktor Vorobjov
tagline: Odoo Developer
email: vostraga@gmail.com
description: "Viktor blog" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Viktor Voroboj, Odoo"
baseurl: "/freshman21" # the subpath of your site, e.g. /blog/
url: ""#"https://straga.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: straga
github_username:  straga
disqus_shortname: straga
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Viktor Vorobjov. I made Odoo modules. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg# your photo.
#google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    lv:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
excerpt_separator: <!-- more -->
